//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asp_mvc_2.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class laporan
    {
        public int id_laporan { get; set; }
        public int id_menu { get; set; }
        public int id_pelanggan { get; set; }
        public string keterangan { get; set; }
        public int meja { get; set; }
        public int quantity { get; set; }
        public int harga { get; set; }
        public int jumlah { get; set; }
    
        public virtual menu menu { get; set; }
        public virtual pelanggan pelanggan { get; set; }
    }
}
